//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.MOL.Your_Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.MOL.Your_Account.TransactionResource", typeof(TransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;package-type-group&apos;]/div/button.
        /// </summary>
        internal static string TransactionPage_FromButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_FromButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div/button.
        /// </summary>
        internal static string TransactionPage_SelectBenefitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionPage_SelectBenefitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;balance-s&apos;]/div[1].
        /// </summary>
        internal static string TransactionsPage_AvailableBalanceValue_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_AvailableBalanceValue_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div[2]/button.
        /// </summary>
        internal static string TransactionsPage_FromDropDown_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromDropDown_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;package-type-group&apos;]/label.
        /// </summary>
        internal static string TransactionsPage_FromLabel_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromLabel_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div/div/ul/li[{0}]/a/span.
        /// </summary>
        internal static string TransactionsPage_GetBenefitName_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_GetBenefitName_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div/div/ul/li.
        /// </summary>
        internal static string TransactionsPage_GetCountOfBenefitfromDropdown_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_GetCountOfBenefitfromDropdown_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/label.
        /// </summary>
        internal static string TransactionsPage_SelectBenefitLabel_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_SelectBenefitLabel_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;transactions-table-0&apos;]/tbody/tr/td[1].
        /// </summary>
        internal static string TransactionsPage_TransactionTable_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_TransactionTable_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div[1]/button.
        /// </summary>
        internal static string TransactionsPage_ViewAccountDropDown_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_ViewAccountDropDown_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div/button.
        /// </summary>
        internal static string TransactionsPage_ViewAccountDropDownonButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_ViewAccountDropDownonButton_Xpath_Locator", resourceCulture);
            }
        }
    }
}
