//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet.IQueuePages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateRequestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateRequestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.IQueuePages.CreateRequestResource", typeof(CreateRequestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;iQueueButton_Add_Note&apos;]/div[1]/div[2].
        /// </summary>
        internal static string CreateRequestPage_AddNoteButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AddNoteButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;MyTabStrip&apos;]/ul/li[3]/a.
        /// </summary>
        internal static string CreateRequestPage_AddNoteTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AddNoteTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoteText.
        /// </summary>
        internal static string CreateRequestPage_AddNoteTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AddNoteTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;iQueueButton_Add_Attachment&apos;]/div[1]/div[2].
        /// </summary>
        internal static string CreateRequestPage_AttachmentAddButton_Id_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AttachmentAddButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AttachmentListWrapper&apos;]/table/tbody/tr.
        /// </summary>
        internal static string CreateRequestPage_AttachmentGrid_Xpath {
            get {
                return ResourceManager.GetString("CreateRequestPage_AttachmentGrid_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div/ul/li[@id=&apos;AttachmentTab&apos;]/a.
        /// </summary>
        internal static string CreateRequestPage_AttachmentTab_Id_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AttachmentTab_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;AddAttachmentWrapper&apos;]/table/tbody/tr[2]/td/input.
        /// </summary>
        internal static string CreateRequestPage_AttachmentTextBox_Xpath_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_AttachmentTextBox_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request_sDescription.
        /// </summary>
        internal static string CreateRequestPage_Description_Id_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_Description_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMSG Automation.
        /// </summary>
        internal static string CreateRequestPage_DescriptionTab_Text {
            get {
                return ResourceManager.GetString("CreateRequestPage_DescriptionTab_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \TestData\Chrysanthemum.jpg.
        /// </summary>
        internal static string CreateRequestPage_FileUploadPath {
            get {
                return ResourceManager.GetString("CreateRequestPage_FileUploadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iframe.
        /// </summary>
        internal static string CreateRequestPage_IFrame_ID {
            get {
                return ResourceManager.GetString("CreateRequestPage_IFrame_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iQueue.
        /// </summary>
        internal static string CreateRequestPage_ParcialTitle_Text {
            get {
                return ResourceManager.GetString("CreateRequestPage_ParcialTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request_iRequestTypeID.
        /// </summary>
        internal static string CreateRequestPage_RequestTypeDropDown_Id_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_RequestTypeDropDown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;iQueueButton_Submit&apos;]/div[@class=&apos;button&apos;].
        /// </summary>
        internal static string CreateRequestPage_SubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("CreateRequestPage_SubmitButton_Xpath_Locator", resourceCulture);
            }
        }
    }
}
