//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplictionForgotPasswordResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplictionForgotPasswordResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.ApplictionForgotPasswordResources", typeof(ApplictionForgotPasswordResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        internal static string ForgotPassword_MOL_ConfirmPasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_ConfirmPasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getCode.
        /// </summary>
        internal static string ForgotPassword_MOL_GetSMSCodeButton_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_GetSMSCodeButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword.
        /// </summary>
        internal static string ForgotPassword_MOL_NewPasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_NewPasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@ class=&apos;success-heading&apos;]/div.
        /// </summary>
        internal static string ForgotPassword_MOL_PasswordResetSuccessful_Text {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_PasswordResetSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSCode.
        /// </summary>
        internal static string ForgotPassword_MOL_SMSCodeTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_SMSCodeTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        internal static string ForgotPassword_MOL_SubmitButton_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_SubmitButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form/section/div/div/input[@class=&apos;formBtn btnReg&apos;].
        /// </summary>
        internal static string ForgotPassword_MOL_UserIdSubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_UserIdSubmitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string ForgotPassword_MOL_UserIdTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_MOL_UserIdTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        internal static string ForgotPassword_ROL_ConfirmPasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_ConfirmPasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getCode.
        /// </summary>
        internal static string ForgotPassword_ROL_GetSMSCodeButton_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_GetSMSCodeButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword.
        /// </summary>
        internal static string ForgotPassword_ROL_NewPasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_NewPasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@ class=&apos;success-heading&apos;]/div.
        /// </summary>
        internal static string ForgotPassword_ROL_PasswordResetSuccessful_Text {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_PasswordResetSuccessful_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMSCode.
        /// </summary>
        internal static string ForgotPassword_ROL_SMSCodeTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_SMSCodeTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        internal static string ForgotPassword_ROL_SubmitButton_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_SubmitButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div[2]/div/div/div[2]/form/a/span.
        /// </summary>
        internal static string ForgotPassword_ROL_UserIdSubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_UserIdSubmitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId.
        /// </summary>
        internal static string ForgotPassword_ROL_UserIdTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ForgotPassword_ROL_UserIdTextBox_Id_Locator", resourceCulture);
            }
        }
    }
}
