//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationRegistrationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationRegistrationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.ApplicationRegistrationResource", typeof(ApplicationRegistrationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string MOLRegisterPage_EmailIdTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_EmailIdTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required.
        /// </summary>
        internal static string MOLRegisterPage_EmpltyEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_EmpltyEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MOLRegisterPage_EmptyEmail_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_EmptyEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/section/div/div[1]/span/span.
        /// </summary>
        internal static string MOLRegisterPage_EmptyEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_EmptyEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxxiainvalidemail.
        /// </summary>
        internal static string MOLRegisterPage_InvalidEmailId_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_InvalidEmailId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is invalid.
        /// </summary>
        internal static string MOLRegisterPage_InvalidEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_InvalidEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/section/div/div[1]/span/span.
        /// </summary>
        internal static string MOLRegisterPage_InvalidEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_InvalidEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/section/div/div[1]/input.
        /// </summary>
        internal static string MOLRegisterPage_RegisterButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_RegisterButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/a/span.
        /// </summary>
        internal static string MOLRegisterPage_SubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_SubmitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/section/div/div[1]/div[2]/div/ul/li.
        /// </summary>
        internal static string MOLRegisterPage_UnregisterdEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("MOLRegisterPage_UnregisterdEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your email address isn’t registered in our system. Please enter the email address that you have registered with us, or you can phone us on 1300 123 123 to register your email address. (Error # 0013).
        /// </summary>
        internal static string MOLRegisterPage_UnRegisteredEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_UnRegisteredEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxxiaunreistermail@mmsg.com.au.
        /// </summary>
        internal static string MOLRegisterPage_UnRegisterEmail_Text {
            get {
                return ResourceManager.GetString("MOLRegisterPage_UnRegisterEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ROLRegisterPage_EmailIdTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ROLRegisterPage_EmailIdTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is required..
        /// </summary>
        internal static string ROLRegisterPage_EmpltyEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_EmpltyEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ROLRegisterPage_EmptyEmail_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_EmptyEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;account-container&apos;]/div/form/div[1]/span.
        /// </summary>
        internal static string ROLRegisterPage_EmptyEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ROLRegisterPage_EmptyEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxxiainvalidemail.
        /// </summary>
        internal static string ROLRegisterPage_InvalidEmailId_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_InvalidEmailId_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email field is not a valid e-mail address..
        /// </summary>
        internal static string ROLRegisterPage_InvalidEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_InvalidEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;account-container&apos;]/div/form/div[1]/span.
        /// </summary>
        internal static string ROLRegisterPage_InvalidEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ROLRegisterPage_InvalidEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/a/span.
        /// </summary>
        internal static string ROLRegisterPage_SubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ROLRegisterPage_SubmitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;register&apos;]/div[4]/div/ul/li.
        /// </summary>
        internal static string ROLRegisterPage_UnregisterdEmailIdErrorMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ROLRegisterPage_UnregisterdEmailIdErrorMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your email address isn’t registered in our system. Please enter the email address that you have registered with us, or you can phone us on 1300 30 40 10 to update your email. (Error # RD 0013).
        /// </summary>
        internal static string ROLRegisterPage_UnRegisteredEmailIdErrorMessage_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_UnRegisteredEmailIdErrorMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxxiaunreistermail@mmsg.com.au.
        /// </summary>
        internal static string ROLRegisterPage_UnRegisterEmail_Text {
            get {
                return ResourceManager.GetString("ROLRegisterPage_UnRegisterEmail_Text", resourceCulture);
            }
        }
    }
}
