//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationLoginPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationLoginPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.ApplicationLoginPageResource", typeof(ApplicationLoginPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxxia Online.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_DashboardPageTitle_Title {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_DashboardPageTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;validation-summary-errors&apos;]/ul/li/p.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_Errormessage_GetText_Xpath {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_Errormessage_GetText_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;login&apos;]/section/div/div[3]/a[2].
        /// </summary>
        internal static string ApplicationLoginPage_MOL_ForgotPassword_Xpath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_ForgotPassword_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your UserID or password was incorrect.  Please try again, or you can phone us on 1300 123 123 for assistance.  (Error # 0019).
        /// </summary>
        internal static string ApplicationLoginPage_MOL_InValidUNandValidPWD_ErroeText {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_InValidUNandValidPWD_ErroeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;col-lg-4 loginCol&apos;]/input[3].
        /// </summary>
        internal static string ApplicationLoginPage_MOL_LoginButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_LoginButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxxia Online..
        /// </summary>
        internal static string ApplicationLoginPage_MOL_LoginPageTitle_Title {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_LoginPageTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_loginuser_ClassName_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_loginuser_ClassName_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class =  &apos;emp-nav-style emp-last&apos;].
        /// </summary>
        internal static string ApplicationLoginPage_MOL_Logout_XPath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_Logout_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_PasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_PasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalidpassword.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_PasswordTextBox_InvalidPassword_Text {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_PasswordTextBox_InvalidPassword_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div[2]/div[2]/div[2]/div[2]/a/span.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_RegistartionButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_RegistartionButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_UserNameTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_UserNameTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestMOLUser.
        /// </summary>
        internal static string ApplicationLoginPage_MOL_UserNameTextBox_InvalidUserName {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_UserNameTextBox_InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your UserID or password was incorrect.  Please try again, or you can phone us on 1300 123 123 for assistance.  (Error # 0019).
        /// </summary>
        internal static string ApplicationLoginPage_MOL_ValidUNandInvalidPWD_ErroeText {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_MOL_ValidUNandInvalidPWD_ErroeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;login&apos;]/div[4]/div[2]/a/span.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_ForgotPassword_Xpath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_ForgotPassword_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_LoginButton_Click_XPath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_LoginButton_Click_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to username.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_loginuser_ClassName_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_loginuser_ClassName_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class =  &apos;emp-nav-style emp-last&apos;].
        /// </summary>
        internal static string ApplicationLoginPage_ROL_Logout_XPath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_Logout_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemServ Online.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_PageTitle_Title {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_PageTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_PasswordTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_PasswordTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div[2]/div[2]/div[2]/div[2]/a/span.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_RegistartionButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_RegistartionButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string ApplicationLoginPage_ROL_UserNameTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ApplicationLoginPage_ROL_UserNameTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 - File or directory not found.
        /// </summary>
        internal static string Login_Page_404Error_Window_Title {
            get {
                return ResourceManager.GetString("Login_Page_404Error_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continueBtn.
        /// </summary>
        internal static string Login_Page_ActivatePage_MOL_ContinueButton_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_MOL_ContinueButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardActivationCode.
        /// </summary>
        internal static string Login_Page_ActivatePage_MOL_LoginActiavtionCodeTextBox_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_MOL_LoginActiavtionCodeTextBox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOBTextBox.
        /// </summary>
        internal static string Login_Page_ActivatePage_MOL_LoginDOB_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_MOL_LoginDOB_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;login&apos;]/section/div/div[1]/input.
        /// </summary>
        internal static string Login_Page_ActivatePage_MOL_RegisterButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_MOL_RegisterButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continueBtn.
        /// </summary>
        internal static string Login_Page_ActivatePage_ROL_ContinueButton_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_ROL_ContinueButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardActivationCode.
        /// </summary>
        internal static string Login_Page_ActivatePage_ROL_LoginActiavtionCodeTextBox_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_ROL_LoginActiavtionCodeTextBox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOBTextBox.
        /// </summary>
        internal static string Login_Page_ActivatePage_ROL_LoginDOB_ID_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_ROL_LoginDOB_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;account-container&apos;]/div[2]/div[2]/a.
        /// </summary>
        internal static string Login_Page_ActivatePage_ROL_RegisterButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("Login_Page_ActivatePage_ROL_RegisterButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Login_Page_AppSetting_RetryCount_Key {
            get {
                return ResourceManager.GetString("Login_Page_AppSetting_RetryCount_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Activate/Verify.
        /// </summary>
        internal static string Login_Page_MOL_Activation {
            get {
                return ResourceManager.GetString("Login_Page_MOL_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;validation-summary-errors&apos;].
        /// </summary>
        internal static string Login_Page_MOL_LoginErrorMessage_XpathLocator {
            get {
                return ResourceManager.GetString("Login_Page_MOL_LoginErrorMessage_XpathLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;validation-summary-errors&apos;]/ul/li/p.
        /// </summary>
        internal static string Login_Page_ROL_LoginErrorMessage_XpathLocator {
            get {
                return ResourceManager.GetString("Login_Page_ROL_LoginErrorMessage_XpathLocator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your account has been suspended because you tried too many times to login with incorrect UserID or password. You can reset your password online, or you can phone us on 1300 30 40 10 for assistance.  (Error # RD 0025).
        /// </summary>
        internal static string Login_Page_ROL_LoginErrorMessageAccountSuspended_Text_Message {
            get {
                return ResourceManager.GetString("Login_Page_ROL_LoginErrorMessageAccountSuspended_Text_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, your UserID or password was incorrect.  Please try again, or you can phone us on 1300 30 40 10 for assistance.  (Error # RD 0019).
        /// </summary>
        internal static string Login_Page_ROL_LoginErrorMessageInvalidPasswordUserName_Text_Message {
            get {
                return ResourceManager.GetString("Login_Page_ROL_LoginErrorMessageInvalidPasswordUserName_Text_Message", resourceCulture);
            }
        }
    }
}
