//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Amendment_BenefitResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Amendment_BenefitResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.Amendment_BenefitResource", typeof(Amendment_BenefitResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtActivationDate_0.
        /// </summary>
        internal static string Amendment_BenefitPage_ActiavateDate_Id_Loctor {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_ActiavateDate_Id_Loctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtActivationDate_0.
        /// </summary>
        internal static string Amendment_BenefitPage_ActivationDateTextBox_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_ActivationDateTextBox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddlBenefits_0.
        /// </summary>
        internal static string Amendment_BenefitPage_BenefitDropDown_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_BenefitDropDown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBudgetAmount_0.
        /// </summary>
        internal static string Amendment_BenefitPage_BudgetAmountTextBox_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_BudgetAmountTextBox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddlBudgetCalcMethod_0.
        /// </summary>
        internal static string Amendment_BenefitPage_BudgetCalculationMenthodDropDown_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_BudgetCalculationMenthodDropDown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddlNextPayDateForChange_0.
        /// </summary>
        internal static string Amendment_BenefitPage_NextPayDateDropDown_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_NextPayDateDropDown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lblPageTitle.
        /// </summary>
        internal static string Amendment_BenefitPage_PageTitle_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_PageTitle_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments - New Benefits.
        /// </summary>
        internal static string Amendment_BenefitPage_PageTitle_Value_Value {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_PageTitle_Value_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnSave.
        /// </summary>
        internal static string Amendment_BenefitPage_SaveButton_ID_Locator {
            get {
                return ResourceManager.GetString("Amendment_BenefitPage_SaveButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Amnedmen {
            get {
                return ResourceManager.GetString("Amnedmen", resourceCulture);
            }
        }
    }
}
