//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AmendmentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmendmentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.AmendmentResource", typeof(AmendmentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdBenefitDetail&apos;]/tbody/tr.
        /// </summary>
        internal static string AmendmentPage_BenefitDetailsTableRow_Xpath_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_BenefitDetailsTableRow_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#wucBenefitDetailsCancelNSave_cmdCancelEnabled.
        /// </summary>
        internal static string AmendmentPage_CancelButton_CssSelelctor_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_CancelButton_CssSelelctor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucBenefitDetailsCancelNSave_cmdCancelEnabled.
        /// </summary>
        internal static string AmendmentPage_CancelButton_ID_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_CancelButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to input#btnNew.
        /// </summary>
        internal static string AmendmentPage_NewButton_CsSelelctor_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_NewButton_CsSelelctor_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnNew.
        /// </summary>
        internal static string AmendmentPage_NewButton_Id_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_NewButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments.
        /// </summary>
        internal static string AmendmentPage_Title_Value {
            get {
                return ResourceManager.GetString("AmendmentPage_Title_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //span[@id=&apos;lblPageTitle&apos;].
        /// </summary>
        internal static string AmendmentPage_Title_Value_Xpath_Locator {
            get {
                return ResourceManager.GetString("AmendmentPage_Title_Value_Xpath_Locator", resourceCulture);
            }
        }
    }
}
