//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CallCentreEnquiryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CallCentreEnquiryResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.CallCentreEnquiryResource", typeof(CallCentreEnquiryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amendments.
        /// </summary>
        internal static string CallCentreEnquiry_Amendment_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Amendment_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgBanner.
        /// </summary>
        internal static string CallCentreEnquiry_ApplictionLogo_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ApplictionLogo_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (.//*[@id=&apos;grdBenefits&apos;]/tbody/tr[2]/td[1]/font/a)[1].
        /// </summary>
        internal static string CallCentreEnquiry_BenefitGrid_Xpath_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_BenefitGrid_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IContent.
        /// </summary>
        internal static string CallCentreEnquiry_BenefitGridFrame_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_BenefitGridFrame_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefits.
        /// </summary>
        internal static string CallCentreEnquiry_Benifit_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Benifit_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div#LeftMenuTree &gt; table:nth-of-type(2) &gt; tbody &gt; tr:nth-of-type(2) &gt; td:nth-of-type(3) &gt; a.
        /// </summary>
        internal static string CallCentreEnquiry_CardIcon_Css_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_CardIcon_Css_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet1.
        /// </summary>
        internal static string CallCentreEnquiry_CarsScreen_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_CarsScreen_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Package.
        /// </summary>
        internal static string CallCentreEnquiry_CreatePackage_LinkText_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_CreatePackage_LinkText_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maxxia Account Snapin.
        /// </summary>
        internal static string CallCentreEnquiry_EAMSProfile_Title {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EAMSProfile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdDOB.
        /// </summary>
        internal static string CallCentreEnquiry_Employee_DOB_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Employee_DOB_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmail.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeEmail_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeEmail_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdGender.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeGender_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeGender_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmployeeName.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeName_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeName_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucPackageSummary_tdEmployeeNo.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeNumber_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeNumber_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;Tablex&apos;]/tbody/tr[2]/td/a.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeNumber_Xpath {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeNumber_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtEmployeeNumber.
        /// </summary>
        internal static string CallCentreEnquiry_EmployeeNumberTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployeeNumberTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtEmployerCode.
        /// </summary>
        internal static string CallCentreEnquiry_EmployerCode_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployerCode_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtEmployerCode.
        /// </summary>
        internal static string CallCentreEnquiry_EmployerCodeTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_EmployerCodeTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdBenefits.
        /// </summary>
        internal static string CallCentreEnquiry_GetBenifitGrid_Status {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_GetBenifitGrid_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmMain.
        /// </summary>
        internal static string CallCentreEnquiry_Iframe_Id {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Iframe_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iframe.
        /// </summary>
        internal static string CallCentreEnquiry_Iframe_TagName_Value {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_Iframe_TagName_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOL Co-Navigation.
        /// </summary>
        internal static string CallCentreEnquiry_MOLCoNav_Link_Title {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_MOLCoNav_Link_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_cmdNew.
        /// </summary>
        internal static string CallCentreEnquiry_NewButton_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_NewButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet14.
        /// </summary>
        internal static string CallCentreEnquiry_NewRequest_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_NewRequest_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet2.
        /// </summary>
        internal static string CallCentreEnquiry_PackageNameWithEmployeeNumber_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_PackageNameWithEmployeeNumber_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu9.
        /// </summary>
        internal static string CallCentreEnquiry_PopUpProcessMenuEditPaymentInstruction_ID_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_PopUpProcessMenuEditPaymentInstruction_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu8.
        /// </summary>
        internal static string CallCentreEnquiry_PopUpProcessMenuViewPaymentInstruction_ID_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_PopUpProcessMenuViewPaymentInstruction_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;tblMain&apos;]/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[13]/td[2]/a.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu__EAMS_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu__EAMS_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu6.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu__NewBenefit_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu__NewBenefit_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.LeftMenuTree_1.LeftMenuTree_4 &gt; a#LeftMenuTreet3.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu_Css_Selector {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu_Css_Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet3.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCESSES.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenu_Title {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu10.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_AdminFrees_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_AdminFrees_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu10.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_EAMS_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_EAMS_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu2.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_Edit_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_Edit_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu5.
        /// </summary>
        internal static string CallCentreEnquiry_ProcessMenuPopUp_ReviewAndActivate_Locator1 {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_ProcessMenuPopUp_ReviewAndActivate_Locator1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet13.
        /// </summary>
        internal static string CallCentreEnquiry_RequestHistory_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_RequestHistory_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_cmdSearch.
        /// </summary>
        internal static string CallCentreEnquiry_SearchButton_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_SearchButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCEmployeeSearch_txtSurname.
        /// </summary>
        internal static string CallCentreEnquiry_SurnametextBox_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_SurnametextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu5i.
        /// </summary>
        internal static string CallCentreEnquiry_TopMenuVehicle_Id_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_TopMenuVehicle_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div/img[@name=&apos;Menu5_1i&apos;].
        /// </summary>
        internal static string CallCentreEnquiry_TopMenuVehicleSearch_Xpath_Locator {
            get {
                return ResourceManager.GetString("CallCentreEnquiry_TopMenuVehicleSearch_Xpath_Locator", resourceCulture);
            }
        }
    }
}
