//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Employee_personaldetailsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Employee_personaldetailsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.Employee_personaldetailsResource", typeof(Employee_personaldetailsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to html/body/form/table/tbody/tr[1]/td/table/tbody/tr[1]/td[2]/font.
        /// </summary>
        internal static string EmployeepersonaldetailsPage__EffectiveDate_Xpath {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage__EffectiveDate_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;BodyColor&apos;]/td[3]/input[4].
        /// </summary>
        internal static string EmployeepersonaldetailsPage__NextButton2_Xpath {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage__NextButton2_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankAccountNumberText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BankAccountNumberText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BankAccountNumberText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77374760.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BankAccountNumberText_Textbox_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BankAccountNumberText_Textbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BankNameText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BankNameText_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BankNameText_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Bank.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BankNameText_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BankNameText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSBNumberText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BSBNumberText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BSBNumberText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 113879.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_BSBNumberText_Textbox_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_BSBNumberText_Textbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09-05-1974.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_DateOfBirth_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_DateOfBirth_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateOfBirthText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_DateOfBirthText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_DateOfBirthText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TitleCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_Dropdown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_Dropdown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_Dropdown_OptionName {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_Dropdown_OptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;frmMain&apos;]/table[1]/tbody/tr[2]/td[2]/table[5]/tbody/tr[1]/td[4]/div/a/img.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EAMS_CancelButton_Name_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EAMS_CancelButton_Name_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frmMain.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EAMS_Frame_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EAMS_Frame_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EffectiveDateText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EffectiveDateText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EffectiveDateText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAddressText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EmailAddressText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EmailAddressText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Address Details.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EmployeeAddressDetailsPage_Title {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EmployeeAddressDetailsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAskedGreenStatementYesRadio.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EmployeeAskedGreenStatementYesRadio_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EmployeeAskedGreenStatementYesRadio_RadioButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeAskedMarketingNoRadio.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EmployeeAskedMarketingNoRadio_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EmployeeAskedMarketingNoRadio_RadioButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_EmployeePage_Title {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_EmployeePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190902.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_ESBMenberNumber_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_ESBMenberNumber_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenderCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_Gender_Dropdown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_Gender_Dropdown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_Gender_Dropdown_Option {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_Gender_Dropdown_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESBMemberNumberText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_GESBMemberNumberText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_GESBMemberNumberText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GivenNameText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_GivenName_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_GivenName_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeAddressLine1Text.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomeAddressLine1Text_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomeAddressLine1Text_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 21  360 ELIZABETH ST.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomeAddressLine1Text_Textbox_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomeAddressLine1Text_Textbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomePostCodeText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomePostCodeText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomePostCodeText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomePostCodeText_Textbox_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomePostCodeText_Textbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeStateCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomeStateCombo_Dropdown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomeStateCombo_Dropdown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HomeSuburbText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomeSuburbText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomeSuburbText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MELBOURNE.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_HomeSuburbText_Textbox_Text {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_HomeSuburbText_Textbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IQueueNumberText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_IQueueNumberText_Textbox_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_IQueueNumberText_Textbox_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_IQueueNumberText_Textbox_Value {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_IQueueNumberText_Textbox_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ppcustomer@mmsg.com.au.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_Mail_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_Mail_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0406 723123.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_MobileNumber_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_MobileNumber_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberMobileText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_MobileNumberText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_MobileNumberText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButtons_cmdNextEnabled.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_NextButton_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_NextButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;BodyColor&apos;]/td[3]/input[3].
        /// </summary>
        internal static string EmployeepersonaldetailsPage_NextButton1_Xpath {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_NextButton1_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OnlineClaimsApprovalRequiredNo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_OnlineClaimsApprovalRequiredNo_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_OnlineClaimsApprovalRequiredNo_RadioButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherNamesText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_OtherNamesText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_OtherNamesText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethodCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PaymentMethodCombo_Dropdown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PaymentMethodCombo_Dropdown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 03 99730006.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PhoneNumber_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PhoneNumber_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumberHomeText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PhoneNumberHomeText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PhoneNumberHomeText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalAddressLine1Text.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PostalAddressLine1Text_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PostalAddressLine1Text_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalPostCodeText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PostalPostCodeText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PostalPostCodeText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalStateCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PostalStateCombo_Dropdown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PostalStateCombo_Dropdown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PostalSuburbText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PostalSuburbText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PostalSuburbText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreferredNameText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_PreferredNameText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_PreferredNameText_Textbox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveMarketingInfoYesRadio.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_ReceiveMarketingInfoYesRadio_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_ReceiveMarketingInfoYesRadio_RadioButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceivePaymentNotificationsYesRadio.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_ReceivePaymentNotificationsYesRadio_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_ReceivePaymentNotificationsYesRadio_RadioButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiveSubstantiationRemindersYesRadio.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_ReceiveSubstantiationRemindersYesRadio_RadioButton_ID {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_ReceiveSubstantiationRemindersYesRadio_RadioButton_ID" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EFTRemittanceMethodCombo.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_RemittanceDropDown_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_RemittanceDropDown_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButtons_cmdSaveEnabled.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_SaveButton_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_SaveButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;BodyColor&apos;]/td[3]/input[2].
        /// </summary>
        internal static string EmployeepersonaldetailsPage_SaveButton_Xpath {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_SaveButton_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurnameText.
        /// </summary>
        internal static string EmployeepersonaldetailsPage_SurnameText_Textbox_ID_Locator {
            get {
                return ResourceManager.GetString("EmployeepersonaldetailsPage_SurnameText_Textbox_ID_Locator", resourceCulture);
            }
        }
    }
}
