//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MotorVehicle_AccessoriesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MotorVehicle_AccessoriesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.MotorVehicle_AccessoriesResource", typeof(MotorVehicle_AccessoriesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtonWebUserControl_cmdAddEnabled.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_AddButton_Id_Loctor {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_AddButton_Id_Loctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdNextEnabled.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_AmuntPageNextButton_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_AmuntPageNextButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtCost.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_CostTxetBox_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_CostTxetBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_CostTxetBox_Value {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_CostTxetBox_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtDescription.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_DescriptionTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_DescriptionTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMSG Automation.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_DescriptionTextBox_Value {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_DescriptionTextBox_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtFBTIncomeComp.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_FBTIncomeComp_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_FBTIncomeComp_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtonWebUserControl_cmdNextEnabled.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_NextButton_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_NextButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPostTaxIncomeComp.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_PostTaxIncomeComp_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_PostTaxIncomeComp_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPreTaxIncomeComp.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_PreTaxIncomeComp_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_PreTaxIncomeComp_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdResults&apos;]/tbody/tr[2].
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_Resultgrid_Xpath_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_Resultgrid_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtTotReqVehicleIncome.
        /// </summary>
        internal static string MotorVehicle_AccessoriesPage_TotalRequestVehicleIncome_Id_Locator {
            get {
                return ResourceManager.GetString("MotorVehicle_AccessoriesPage_TotalRequestVehicleIncome_Id_Locator", resourceCulture);
            }
        }
    }
}
