//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Package_basedetailsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Package_basedetailsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.Package_basedetailsResource", typeof(Package_basedetailsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBusinessEmail.
        /// </summary>
        internal static string Package_basedetailsPage_BusinesEmail_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_BusinesEmail_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdNextEnabled.
        /// </summary>
        internal static string Package_basedetailsPage_EditPackage_NextButton_Id {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_EditPackage_NextButton_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;LeftMenu_tblLeftMenu&apos;]/tbody/tr[6]/td[3].
        /// </summary>
        internal static string Package_basedetailsPage_EditPackage_PackageAdminDetails_Xpath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_EditPackage_PackageAdminDetails_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //td/span[@id=&apos;lblPageTitle&apos;].
        /// </summary>
        internal static string Package_basedetailsPage_EditPackage_PageHeading_Xpath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_EditPackage_PageHeading_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;LeftMenu_tblLeftMenu&apos;]/tbody/tr[7]/td[3].
        /// </summary>
        internal static string Package_basedetailsPage_EditPackage_PayrollDetails_Xpath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_EditPackage_PayrollDetails_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtBusinessTelephone.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_BusinessTelephone_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_BusinessTelephone_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgEmployerLookup.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_EmployerLookup_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_EmployerLookup_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdNextEnabled.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_NextButton_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_NextButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;BodyColor&apos;]/td[3]/input[3].
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_NextButton_Xpath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_NextButton_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddmEmployerOfferingID_txtDisplay.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_OfferingTextbox_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_OfferingTextbox_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peninsula Health.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_OfferingTextbox_Text {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_OfferingTextbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr#ddmEmployerOfferingID_trMain &gt; td &gt; input.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_OffreingImage_Dropdown_CssSelelctor {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_OffreingImage_Dropdown_CssSelelctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;ddmEmployerOfferingID_trMain&apos;]/td[2]/img.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_OffreingImage_Dropdown_XPath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_OffreingImage_Dropdown_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;divMenuddmEmployerOfferingID&apos;]/table/tbody/tr[2]/td[1].
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_OffreingTable_Dropdown_XPath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_OffreingTable_Dropdown_XPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultsGrid.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_ResultGrid_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_ResultGrid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table [@id=&apos;ResultsGrid&apos;]/tbody/tr[2]/td[1]/a.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_SearchEmployer_EmployeerLink_Xpath {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_SearchEmployer_EmployeerLink_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchButton.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_SearchEmployer_SearchButton_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_SearchEmployer_SearchButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployerCodeText.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_SearchEmployer_Textbox_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_SearchEmployer_Textbox_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_SearchEmployer_Title {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_SearchEmployer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cboSetUpReason.
        /// </summary>
        internal static string Package_basedetailsPage_NewPackage_SetupReason_Dropdown_ID {
            get {
                return ResourceManager.GetString("Package_basedetailsPage_NewPackage_SetupReason_Dropdown_ID", resourceCulture);
            }
        }
    }
}
