//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Package_payrolldetailsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Package_payrolldetailsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.Package_payrolldetailsResource", typeof(Package_payrolldetailsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdAddEnabled.
        /// </summary>
        internal static string Package_payrolldetailsPage__AddButton_ID {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage__AddButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wucButtons_cmdSaveEnabled.
        /// </summary>
        internal static string Package_payrolldetailsPage_Edit_SaveButton_ID {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_Edit_SaveButton_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@id=&apos;ddmPayCycleID_trMain&apos;]/td/input.
        /// </summary>
        internal static string Package_payrolldetailsPage_PayCycle_Textbox_Xpath {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_PayCycle_Textbox_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;divMenuddmPayCycleID&apos;]/table/tbody/tr[2]/td[1].
        /// </summary>
        internal static string Package_payrolldetailsPage_PayCycleTable_Textbox_Xpath {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_PayCycleTable_Textbox_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to txtPayrollID.
        /// </summary>
        internal static string Package_payrolldetailsPage_Payroll_Textbox_ID {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_Payroll_Textbox_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grdResults.
        /// </summary>
        internal static string Package_payrolldetailsPage_ResultGrid_ID {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_ResultGrid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;grdResults&apos;]/tbody/tr[2]/td[1].
        /// </summary>
        internal static string Package_payrolldetailsPage_ResultGrid_Xpath_Locator {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_ResultGrid_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;BodyColor&apos;]/td[3]/input[2].
        /// </summary>
        internal static string Package_payrolldetailsPage_SaveButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("Package_payrolldetailsPage_SaveButton_Xpath_Locator", resourceCulture);
            }
        }
    }
}
