//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PaymentInstructionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PaymentInstructionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.PaymentInstructionResource", typeof(PaymentInstructionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButtons$cmdAddEnabled.
        /// </summary>
        internal static string PaymentInstruction_AddButton_Name_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_AddButton_Name_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string PaymentInstruction_Amount_GSTInclusive_Value {
            get {
                return ResourceManager.GetString("PaymentInstruction_Amount_GSTInclusive_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButtons_cmdCancelEnabled.
        /// </summary>
        internal static string PaymentInstruction_CancelButton_ID_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_CancelButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmdYes.
        /// </summary>
        internal static string PaymentInstruction_ConfermationYesButton_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_ConfermationYesButton_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ResultsGrid&apos;]/tbody/tr[2]/td[3].
        /// </summary>
        internal static string PaymentInstruction_Grid_Xapth_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_Grid_Xapth_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to imgpayeeLookup.
        /// </summary>
        internal static string PaymentInstruction_PayeeLookUpImg_ID_Loacator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PayeeLookUpImg_ID_Loacator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@id=&apos;ResultsGrid&apos;]/tbody/tr[2]/td[2]/a.
        /// </summary>
        internal static string PaymentInstruction_PayeePopUpGrid_Xpath_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PayeePopUpGrid_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iframe.
        /// </summary>
        internal static string PaymentInstruction_PayeePopUpIframe_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PayeePopUpIframe_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchButton.
        /// </summary>
        internal static string PaymentInstruction_PayeePopUpPayeeSearchButton_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PayeePopUpPayeeSearchButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayeeNameText.
        /// </summary>
        internal static string PaymentInstruction_PayeePopUpPayeeTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PayeePopUpPayeeTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentAmountText.
        /// </summary>
        internal static string PaymentInstruction_PaymentAmountTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentAmountTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentDescriptionText.
        /// </summary>
        internal static string PaymentInstruction_PaymentDiscriptionTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentDiscriptionTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentDueDateText.
        /// </summary>
        internal static string PaymentInstruction_PaymentDueDate_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentDueDate_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentFrequencyCombo.
        /// </summary>
        internal static string PaymentInstruction_PaymentFrequencyDropdown_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentFrequencyDropdown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentReferenceText.
        /// </summary>
        internal static string PaymentInstruction_PaymentReferencesTextBox_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentReferencesTextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TerminateDateText.
        /// </summary>
        internal static string PaymentInstruction_PaymentTerminationDate_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentTerminationDate_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentTypeCombo.
        /// </summary>
        internal static string PaymentInstruction_PaymentTypeDropdown_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_PaymentTypeDropdown_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TITLE.
        /// </summary>
        internal static string PaymentInstruction_PopupTitle_Text {
            get {
                return ResourceManager.GetString("PaymentInstruction_PopupTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommandButtons_cmdSaveEnabled.
        /// </summary>
        internal static string PaymentInstruction_SaveButton_Id_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_SaveButton_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResultsGrid.
        /// </summary>
        internal static string PaymentInstruction_SearchResultGrid_Id {
            get {
                return ResourceManager.GetString("PaymentInstruction_SearchResultGrid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string PaymentInstruction_SearchTitle_Text {
            get {
                return ResourceManager.GetString("PaymentInstruction_SearchTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payee 1000.
        /// </summary>
        internal static string PaymentInstruction_TextBoxPayee_Value {
            get {
                return ResourceManager.GetString("PaymentInstruction_TextBoxPayee_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div/span[@id=&apos;PageTitle&apos;].
        /// </summary>
        internal static string PaymentInstruction_Title_Xapth_Locator {
            get {
                return ResourceManager.GetString("PaymentInstruction_Title_Xapth_Locator", resourceCulture);
            }
        }
    }
}
