//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.Comet {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerifyBudgetAmountTransactionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerifyBudgetAmountTransactionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.Comet.VerifyBudgetAmountTransactionResource", typeof(VerifyBudgetAmountTransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table[1]/tbody/tr[2]/td[2]/table[4]/tbody/tr.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_CountOfSysyem_Xpath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_CountOfSysyem_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table[1]/tbody/tr[2]/td[2]/table[4]/tbody/tr[4]/td[1]/a/img.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_DeLinkButon_Xpath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_DeLinkButon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopUpMenu_cmdMenu10.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_EAMS_Id_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_EAMS_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table/tbody/tr[2]/td[2]/table[4]/tbody/tr[{0}]/td[6].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_EmployeeName_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_EmployeeName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;wucPackageSummary_tdEmployeeNo&apos;]/a.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_EmployeeNum_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_EmployeeNum_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table/tbody/tr[2]/td[2]/table[4]/tbody/tr[{0}]/td[5].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_GivenName_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_GivenName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table/tbody/tr[2]/td[2]/table[4]/tbody/tr[{0}]/td[7].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_LastName_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_LastName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table[1]/tbody/tr[2]/td[2]/table[8]/tbody/tr[1]/td[1]/a/img.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_LinkButon_Xpath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_LinkButon_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //tr[@class=&apos;TableBackgroundDark&apos;]/td[3]/input.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_MOLUserName_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_MOLUserName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table/tbody/tr[2]/td[2]/table[4]/tbody/tr[{0}]/td[1].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_SystemName_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_SystemName_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTree.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_TreeView_Id_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_TreeView_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //form[@id=&apos;frmMain&apos;]/table/tbody/tr[2]/td[2]/table[4]/tbody/tr[{0}]/td[2].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_VMSAccuntIsPresent_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_VMSAccuntIsPresent_XPath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMenuTreet6.
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_VMSBalance_ID_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_VMSBalance_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@id=&apos;LeftMenuTreet2&apos;].
        /// </summary>
        internal static string VerifyBudgetAmountTransactionPage_VMSBalance_XPath_Locator {
            get {
                return ResourceManager.GetString("VerifyBudgetAmountTransactionPage_VMSBalance_XPath_Locator", resourceCulture);
            }
        }
    }
}
