//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Automation.Database_Support.DBDataTransferObjects {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DBUserQueriesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DBUserQueriesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Automation.Database_Support.DBDataTransferObjects.DBUserQueriesResource", typeof(DBUserQueriesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database_Support.
        /// </summary>
        internal static string DatabaseSupport_FolderName {
            get {
                return ResourceManager.GetString("DatabaseSupport_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBDataTransferObjects.
        /// </summary>
        internal static string DBDataTransferObjects_FolderName {
            get {
                return ResourceManager.GetString("DBDataTransferObjects_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSAOnline4.
        /// </summary>
        internal static string DBUserQueries_NewConnectionString_Key {
            get {
                return ResourceManager.GetString("DBUserQueries_NewConnectionString_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.usp_DM_PopulateProfiles.
        /// </summary>
        internal static string DBUserQueries_PopulateEmpProfile_StoreProcedure_Name {
            get {
                return ResourceManager.GetString("DBUserQueries_PopulateEmpProfile_StoreProcedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comet.
        /// </summary>
        internal static string DBUserQueries_Product_Name {
            get {
                return ResourceManager.GetString("DBUserQueries_Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisableSMSValidationInActivationSite.
        /// </summary>
        internal static string DisableSMSValidationInActivationSite_FileName {
            get {
                return ResourceManager.GetString("DisableSMSValidationInActivationSite_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnableTheSMSValidation.
        /// </summary>
        internal static string EnableTheSMSValidatio_FileName {
            get {
                return ResourceManager.GetString("EnableTheSMSValidatio_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1  CONCAT(iEmployeeExtIDBase , iEmployeeExtIDCheckDigit) as EmployeeNo FROM [tbl_Employee] ORDER BY NEWID().
        /// </summary>
        internal static string FetchEmployeeNumber {
            get {
                return ResourceManager.GetString("FetchEmployeeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Populate Profile.
        /// </summary>
        internal static string StoreProc_PopulateEmployeeProfile {
            get {
                return ResourceManager.GetString("StoreProc_PopulateEmployeeProfile", resourceCulture);
            }
        }
    }
}
