//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.MOL.Home.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PayrollDeductionsAndTransfersPageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PayrollDeductionsAndTransfersPageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.MOL.Home.Dashboard.PayrollDeductionsAndTransfersPageResource", typeof(PayrollDeductionsAndTransfersPageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[2]/a.
        /// </summary>
        internal static string PayrollDeductionsAndTransfers_30DaysTransationTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("PayrollDeductionsAndTransfers_30DaysTransationTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[3]/a.
        /// </summary>
        internal static string PayrollDeductionsAndTransfers_60Days_Xpath_Locator {
            get {
                return ResourceManager.GetString("PayrollDeductionsAndTransfers_60Days_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to active.
        /// </summary>
        internal static string PayrollDeductionsAndTransfers_ActiveTabStatus_Text {
            get {
                return ResourceManager.GetString("PayrollDeductionsAndTransfers_ActiveTabStatus_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[4]/a.
        /// </summary>
        internal static string PayrollDeductionsAndTransfers_AdvanceFilterTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("PayrollDeductionsAndTransfers_AdvanceFilterTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/h1/span.
        /// </summary>
        internal static string PayrollDeductionsAndTransfers_PayrollDeductionsAndTransfersTitle_Xpath_Locator {
            get {
                return ResourceManager.GetString("PayrollDeductionsAndTransfers_PayrollDeductionsAndTransfersTitle_Xpath_Locator", resourceCulture);
            }
        }
    }
}
