//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.ROL.Your_Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.ROL.Your_Account.TransactionResource", typeof(TransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[2]/a.
        /// </summary>
        internal static string TransactionsPage_30daysTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_30daysTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[3]/a.
        /// </summary>
        internal static string TransactionsPage_60daysTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_60daysTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[1]/a.
        /// </summary>
        internal static string TransactionsPage_7daysTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_7daysTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@id=&apos;tabs&apos;]/li[4]/a.
        /// </summary>
        internal static string TransactionsPage_AdvancesFilterdaysTab_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_AdvancesFilterdaysTab_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;balance&apos;]/div/b.
        /// </summary>
        internal static string TransactionsPage_AvailableBalanceValue_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_AvailableBalanceValue_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[@class=&apos;ui-datepicker-calendar&apos;]//tr//td/a[contains(text(),&apos;{0}&apos;)].
        /// </summary>
        internal static string TransactionsPage_FromDate_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromDate_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (//span[@class=&apos;date-picker-container&apos;])[1]/img.
        /// </summary>
        internal static string TransactionsPage_FromDatePickerImg_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromDatePickerImg_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div[2]/button.
        /// </summary>
        internal static string TransactionsPage_FromDropDown_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromDropDown_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/label[2].
        /// </summary>
        internal static string TransactionsPage_FromLabel_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromLabel_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@title=&apos;Prev&apos;].
        /// </summary>
        internal static string TransactionsPage_FromPrev_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_FromPrev_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@id=&apos;submit-form&apos;].
        /// </summary>
        internal static string TransactionsPage_SubmitButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_SubmitButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (//span[@class=&apos;date-picker-container&apos;])[2]/img.
        /// </summary>
        internal static string TransactionsPage_ToDate_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_ToDate_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/div[1]/button.
        /// </summary>
        internal static string TransactionsPage_ViewAccountDropDown_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_ViewAccountDropDown_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;title&apos;]/div/form/label[1].
        /// </summary>
        internal static string TransactionsPage_ViewAccountLabel_Xpath_Locator {
            get {
                return ResourceManager.GetString("TransactionsPage_ViewAccountLabel_Xpath_Locator", resourceCulture);
            }
        }
    }
}
