//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.ROL.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangePasswordResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangePasswordResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.ROL.Profile.ChangePasswordResources", typeof(ChangePasswordResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OldPassword.
        /// </summary>
        internal static string ChangePasswordPage_CurrentPassword_TextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_CurrentPassword_TextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current password field is required..
        /// </summary>
        internal static string ChangePasswordPage_CurrentPasswordMessage_PasswordRequired_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_CurrentPasswordMessage_PasswordRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div/form/div/div[2]/div[3]/span/span.
        /// </summary>
        internal static string ChangePasswordPage_CurrentPasswordValidationMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_CurrentPasswordValidationMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password1234.
        /// </summary>
        internal static string ChangePasswordPage_InvalidValidPassword_Password1234_Text {
            get {
                return ResourceManager.GetString("ChangePasswordPage_InvalidValidPassword_Password1234_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewPassword.
        /// </summary>
        internal static string ChangePasswordPage_NewPassword_TextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_NewPassword_TextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New password field is required..
        /// </summary>
        internal static string ChangePasswordPage_NewPasswordPasswordMessage_PasswordRequired_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_NewPasswordPasswordMessage_PasswordRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password must be between six and 15 characters long and contain upper and lower case letters and numbers..
        /// </summary>
        internal static string ChangePasswordPage_NewPasswordPasswordMessage_UpperCaseLowerCase15CharRequiredMessage_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_NewPasswordPasswordMessage_UpperCaseLowerCase15CharRequiredMes" +
                        "sage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div/form/div/div[3]/div[3]/span/span.
        /// </summary>
        internal static string ChangePasswordPage_NewPasswordValidationMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_NewPasswordValidationMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmPassword.
        /// </summary>
        internal static string ChangePasswordPage_ReEnterNewPassword_TextBox_Id_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ReEnterNewPassword_TextBox_Id_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both of the new passwords must match.
        /// </summary>
        internal static string ChangePasswordPage_ReEnterNewPasswordMessage_NewPasswordReEnterPasswordBothMatch_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ReEnterNewPasswordMessage_NewPasswordReEnterPasswordBothMatch_" +
                        "Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Re-enter new password field is required..
        /// </summary>
        internal static string ChangePasswordPage_ReEnterNewPasswordMessage_PasswordRequired_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ReEnterNewPasswordMessage_PasswordRequired_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Re-enter new password must be a string with a minimum length of 6 and a maximum length of 15..
        /// </summary>
        internal static string ChangePasswordPage_ReEnterNewPasswordPasswordMessage_UpperCaseLowerCase15CharRequiredMessage_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ReEnterNewPasswordPasswordMessage_UpperCaseLowerCase15CharRequ" +
                        "iredMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div/form/div/div[4]/div[3]/span/span.
        /// </summary>
        internal static string ChangePasswordPage_ReEnterNewPasswordValidationMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ReEnterNewPasswordValidationMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div/div/form/div[2]/button.
        /// </summary>
        internal static string ChangePasswordPage_SaveChanges_Button_Xpath_Locator {
            get {
                return ResourceManager.GetString("ChangePasswordPage_SaveChanges_Button_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password has been changed..
        /// </summary>
        internal static string ChangePasswordPage_SuccessMessage_Message {
            get {
                return ResourceManager.GetString("ChangePasswordPage_SuccessMessage_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;introduction&apos;]/span[1]/p[2].
        /// </summary>
        internal static string ChangePasswordPage_SuccessMessage_Xpath_Loctor {
            get {
                return ResourceManager.GetString("ChangePasswordPage_SuccessMessage_Xpath_Loctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password123.
        /// </summary>
        internal static string ChangePasswordPage_ValidPassword_Password123_Text {
            get {
                return ResourceManager.GetString("ChangePasswordPage_ValidPassword_Password123_Text", resourceCulture);
            }
        }
    }
}
