//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.MOL.Claims {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectBenefitResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectBenefitResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.MOL.Claims.SelectBenefitResource", typeof(SelectBenefitResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benefitgroup0.
        /// </summary>
        internal static string SelelctBenefit_BenefitRadiobutton_ID_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_BenefitRadiobutton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/form/div[1]/div/div[6]/div/span[2]/p[2].
        /// </summary>
        internal static string SelelctBenefit_NoReimbusmentMessge_Xpath_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_NoReimbusmentMessge_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is currently no reimbursement bank account listed on your.
        /// </summary>
        internal static string SelelctBenefit_NoReimbusmentText_Text {
            get {
                return ResourceManager.GetString("SelelctBenefit_NoReimbusmentText_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;panel-content&apos;]/div/span[2]/p[2].
        /// </summary>
        internal static string SelelctBenefit_NoReimbusmentText_Xpath_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_NoReimbusmentText_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian Expenses.
        /// </summary>
        internal static string SelelctBenefit_PageTitle_AustralianExpress_LinkText {
            get {
                return ResourceManager.GetString("SelelctBenefit_PageTitle_AustralianExpress_LinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //ul[@class=&apos;dropdown-menu inner selectpicker&apos;]/li[2]/a.
        /// </summary>
        internal static string SelelctBenefit_PageTitle_ExpenceDropdownFirstOption_List_Xpath {
            get {
                return ResourceManager.GetString("SelelctBenefit_PageTitle_ExpenceDropdownFirstOption_List_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //button[@class=&apos;btn dropdown-toggle selectpicker select-btn form-control&apos;].
        /// </summary>
        internal static string SelelctBenefit_PageTitle_ExpenceDropdownOption_List_Xpath {
            get {
                return ResourceManager.GetString("SelelctBenefit_PageTitle_ExpenceDropdownOption_List_Xpath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/form/div[1]/div/div[1]/div.
        /// </summary>
        internal static string SelelctBenefit_PageTitle_Xpath_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_PageTitle_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProcessDisclaimerButton.
        /// </summary>
        internal static string SelelctBenefit_ProcessMenuButton_ID_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_ProcessMenuButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;select-benefit-button&apos;]/button.
        /// </summary>
        internal static string SelelctBenefit_StartReimbursementButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("SelelctBenefit_StartReimbursementButton_Xpath_Locator", resourceCulture);
            }
        }
    }
}
