//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.MOL.Claims {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SubmitClaimResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitClaimResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.MOL.Claims.SubmitClaimResource", typeof(SubmitClaimResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcceptDeclarationCheckBox.
        /// </summary>
        internal static string SubmitClaimPage_AcceptDeclarationCheckBox_ID_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_AcceptDeclarationCheckBox_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate-modal.
        /// </summary>
        internal static string SubmitClaimPage_DuplictaeModule_ID_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_DuplictaeModule_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnProceed.
        /// </summary>
        internal static string SubmitClaimPage_PopUpProceedButton_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_PopUpProceedButton_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit-claim-proceed.
        /// </summary>
        internal static string SubmitClaimPage_ProceedButton_ID_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_ProceedButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your claim has been successfully submitted.
        /// </summary>
        internal static string SubmitClaimPage_SuccessMessage_Text {
            get {
                return ResourceManager.GetString("SubmitClaimPage_SuccessMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div[1]/div/div[3]/div/div[2]/div.
        /// </summary>
        internal static string SubmitClaimPage_SuccessMessage_Xpath_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_SuccessMessage_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //p/strong.
        /// </summary>
        internal static string SubmitClaimPage_SuccessMessageStrong_Xpath_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_SuccessMessageStrong_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@id=&apos;content&apos;]/div[1]/div[1]/div[1]/div[2]/div.
        /// </summary>
        internal static string SubmitClaimPage_Title_Xpath_Locator {
            get {
                return ResourceManager.GetString("SubmitClaimPage_Title_Xpath_Locator", resourceCulture);
            }
        }
    }
}
