//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMSG.Pages.UI_Pages.MOL.Claims {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadReceiptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadReceiptResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MMSG.Pages.UI_Pages.MOL.Claims.UploadReceiptResource", typeof(UploadReceiptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrysanthemum.
        /// </summary>
        internal static string Chrysanthemum_FileName {
            get {
                return ResourceManager.GetString("Chrysanthemum_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestData.
        /// </summary>
        internal static string TestData_FolderName {
            get {
                return ResourceManager.GetString("TestData_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .//*[@id=&apos;MainForm&apos;]/div[1]/div/div[3]/div[2]/div/div/div[1]/div/div[4]/span.
        /// </summary>
        internal static string UploadReceiptPage_IndividualInvoicesUploadButton_Xpath_Locator {
            get {
                return ResourceManager.GetString("UploadReceiptPage_IndividualInvoicesUploadButton_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;content-highlight border-top-panel&apos;]/div.
        /// </summary>
        internal static string UploadReceiptPage_PageTitle_Xpath_Locator {
            get {
                return ResourceManager.GetString("UploadReceiptPage_PageTitle_Xpath_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProceedButton.
        /// </summary>
        internal static string UploadReceiptPage_ProcessedButton_ID_Locator {
            get {
                return ResourceManager.GetString("UploadReceiptPage_ProcessedButton_ID_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@class=&apos;fileupload-progress-container&apos;]/div[2].
        /// </summary>
        internal static string UploadReceiptPage_UploadSuccessIcon_Xpath_Locator {
            get {
                return ResourceManager.GetString("UploadReceiptPage_UploadSuccessIcon_Xpath_Locator", resourceCulture);
            }
        }
    }
}
